### ISSUE TITLE
Two test failures on OpenBSD

### ISSUE THREAD

**Issue by bentley** [sustrik/libdill#145]
Testing with libdill-2.4 on OpenBSD -current, tests/go and tests/udp fail.

go.log:

    Segmentation fault (core dumped)
    FAIL tests/go (exit status: 139)

    Program received signal SIGSEGV, Segmentation fault.
    0x0000068bc0f597c9 in dill_pollset_poll (timeout=40) at ./kqueue.c.inc:212
    212         struct dill_ctx_pollset *ctx = &dill_getctx->pollset;
    (gdb) bt
    #0  0x0000068bc0f597c9 in dill_pollset_poll (timeout=40) at ./kqueue.c.inc:212
    #1  0x0000068bc0f583e8 in dill_wait () at cr.c:481
    #2  0x0000068955b00fa5 in main () at tests/go.c:130

udp.log:

    assertion "rc == 0" failed: file "tests/udp.c", line 44, function "main"
    Abort trap (core dumped)
    FAIL tests/udp (exit status: 134)

**Comment by sustrik** [comment]
I've modified udp.c to print out the errno. Can you try again with the head?

As for the go test, I don't have an OpenBSD box, so I can't debug it. Can you possibly run it under debugger and check what's happening? AFAICS the dill_getctx_() function (defined in ctx.c) is returning NULL. The function itself contains only few POSIX calls so it shouldn't be hard to find out what's going on.

**Comment by bentley** [comment]
Network is unreachable [51] (tests/udp.c:44)

Don’t really have time to look at go at the moment.

**Comment by sustrik** [comment]
Ok, I think I have fixed the UDP problem. Can you try now?

**Comment by sustrik** [comment]
I've also found this: "NetBSD and OpenBSD will probably need DILL_THREAD_FALLBACK to work as they don't have support for thread local storage."

But it's strange that other tests work. Maybe OpenBSD has TLS after all?

**Comment by bentley** [comment]
UDP still fails:

    Network is unreachable [51] (tests/udp.c:58)
    Abort trap (core dumped) 
    FAIL tests/udp (exit status: 134)

OpenBSD doesn’t have TLS, but I believe LLVM provides some sort of TLS emulation, although I don’t know the specifics.

**Comment by sustrik** [comment]
ENETUNREACH means that the network is not reachable. Is you machine on the net? Alternatively, maybe OpenBSD has some paranoid setting that disables UDP?

As for the TLS stuff, there's a fallback mode. Try configuring like this:

./configure CFLAGS='-DDILL_THREAD_FALLBACK

If it works I'll set it as a default for OpenBSD.

**Comment by bentley** [comment]
The machine is on the net—I’m replying from it.

-DDILL_THREAD_FALLBACK made no difference; the same two tests fail.
